project:
  type: website
  output-dir: docs

website:
  title: "Kate Frankland"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: about me
        menu:
          - text: Pets
            href: pets.qmd
          - text: Baking
            href: baking.qmd
          - text: What's Next?
            href: whats_next.qmd
      - href: projects.qmd
        text: Projects
      - href: Hobbies.qmd
        text: Hobbies
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    font: URWGothic
    page-layout: full

editor: visual
